#!/bin/sh
BGSELECT="#B294BB"
FG="#6F7277"
BG="#34322E"
#BG="#85678F"
FONT="-*-Inconsolata-*-*-*-*-28-*-*-*-*-*-*-*"
FONT="-*-lemon-*-*-*-*-16-*-*-*-*-*-*-*"
FONT="-*-fixed-*-*-*-*-20-*-*-*-*-*-*-*"
dmenu_run -fn ${FONT} -nb $BG -nf $FG -sb $BGSELECT
